services:
  app:
    networks:
      default:
      proxy:
        aliases:
          - haccp-monitor
  demo:
    environment:
      DEMO_API_URL: https://haccp.pow24.org

networks:
  proxy:
    external: true
    name: proxy
